name: 'GroupMe Action Notifier'
description: 'send groupme messages'
author: 'nhomble'
inputs:
  group:
    description: 'group to notify'
    required: true
  message:
    description: 'message to send'
    required: true
  token:
    description: 'groupme api key'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'message-square'
  color: 'blue'
