name: 'groupme-notify-action'
description: 'send groupme messages'
inputs:
  group-id:
    description: 'group to notify'
    required: true
  message:
    description: 'message to send'
    required: true
  groupme-token:
    description: 'groupme api key'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.group-id }}
    - ${{ inputs.message }}
  env:
    GROUPME_API_TOKEN: ${{ inputs.groupme-token }}