name: 'groupme-notify-action'
description: 'send groupme messages'
inputs:
  group:
    description: 'group to notify'
    required: true
  message:
    description: 'message to send'
    required: true
  token:
    description: 'groupme api key'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'