name: 'GroupMe Action Notifier'
description: 'send groupme messages'
author: 'nhomble'
inputs:
  group:
    description: 'groupId to notify, this argument is optional and ignored if `bot` is defined'
    required: false
  bot:
    description: 'botId to use for notification, this argument can be null if `group` is defined '
    required: false
  message:
    description: 'message to send'
    required: true
  token:
    description: 'groupme api key'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'message-square'
  color: 'blue'
