#!/bin/sh -l

export GO_GROUPME_API_TOKEN=$INPUT_TOKEN

MSG << END
Repository: $GITHUB_REPOSITORY
Running: ${GITHUB_WORKFLOW}/${GITHUB_JOB/GITHUB_RUN_ID/GITHUB_REF}
By: ${GITHUB_ACTOR}

$INPUT_MESSAGE
END

/notify -groupId $INPUT_GROUP -m "$MSG"
