name: groupme-notify
on: [push]

jobs:
  groupme:
    runs-on: ubuntu-latest
    name: notify
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com          
          username: ${{ secrets.MY_GITHUB_DOCKER_USERNAME }}
          password: ${{ secrets.MY_GITHUB_DOCKER_SECRET }}        
      - name: do notification
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          group-id: ${{ secrets.GROUPME_GROUP }}
          message: 'groupme-notify-action is job ran'
          groupme-token: ${{ secrets.GO_GROUPME_API_TOKEN }}