name: groupme-notify
on: [push]

jobs:
  groupme:
    runs-on: ubuntu-latest
    name: notify
    steps:
      - name: Checkout
        uses: actions/checkout@v2     
      - name: do notification as me
        uses: ./ 
        id: me
        with:
          group: ${{ secrets.GROUPME_GROUP }}
          message: "Hey it's me!"
          token: ${{ secrets.GO_GROUPME_API_TOKEN }}
      - name: do notification as bot
        uses: ./ 
        id: bot
        with:
          bot: ${{ secrets.GROUPME_BOT }}
          message: "It's a bot!"
          token: ${{ secrets.GO_GROUPME_API_TOKEN }}
